name: NPM Publish
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout Code"
      uses: actions/checkout@v4
    - name: "Setup Environment"
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: npm ci
    - name : "Run Tests"
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: npm test
    - name: "Publish to NPM"
      if: github.event_name == 'release'
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM }}
    - name: "Upload npm package to Release"
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GHPAT }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: type-on-path-*.tgz
        asset_content_type: application/gzip
